In [56]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# from sklearn.preprocessing import  LabelEncoder, StandardScaler
# from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score, KFold
# from sklearn import metrics
# from sklearn.linear_model import LinearRegression
# from sklearn.preprocessing import PolynomialFeatures
# from sklearn.pipeline import Pipeline
# from sklearn.ensemble import GradientBoostingRegressor
# from xgboost import XGBRegressor
# from sklearn.ensemble import RandomForestRegressor

In [57]:
df = pd.read_csv("./train.csv")

In [58]:
df.head()

,id,log_price,property_type,room_type,amenities,accommodates,bathrooms,bed_type,cancellation_policy,cleaning_fee,...,latitude,longitude,name,neighbourhood,number_of_reviews,review_scores_rating,thumbnail_url,zipcode,bedrooms,beds
0,6901257,5.010635,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",3,1.0,Real Bed,strict,True,...,40.696524,-73.991617,Beautiful brownstone 1-bedroom,Brooklyn Heights,2,100.0,https://a0.muscache.com/im/pictures/6d7cbbf7-c...,11201,1.0,1.0
1,6304928,5.129899,Apartment,Entire home/apt,"{""Wireless Internet"",""Air conditioning"",Kitche...",7,1.0,Real Bed,strict,True,...,40.766115,-73.989040,Superb 3BR Apt Located Near Times Square,Hell's Kitchen,6,93.0,https://a0.muscache.com/im/pictures/348a55fe-4...,10019,3.0,3.0
2,7919400,4.976734,Apartment,Entire home/apt,"{TV,""Cable TV"",""Wireless Internet"",""Air condit...",5,1.0,Real Bed,moderate,True,...,40.808110,-73.943756,The Garden Oasis,Harlem,10,92.0,https://a0.muscache.com/im/pictures/6fae5362-9...,10027,1.0,3.0
3,13418779,6.620073,House,Entire home/apt,"{TV,""Cable TV"",Internet,""Wireless Internet"",Ki...",4,1.0,Real Bed,flexible,True,...,37.772004,-122.431619,Beautiful Flat in the Heart of SF!,Lower Haight,0,NaN,https://a0.muscache.com/im/pictures/72208dad-9...,94117,2.0,2.0
4,3808709,4.744932,Apartment,Entire home/apt,"{TV,Internet,""Wireless Internet"",""Air conditio...",2,1.0,Real Bed,moderate,True,...,38.925627,-77.034596,Great studio in midtown DC,Columbia Heights,4,40.0,NaN,20009,0.0,1.0

In [59]:
df.shape

(74111, 29)

In [60]:
df.columns

Index(['id', 'log_price', 'property_type', 'room_type', 'amenities',
       'accommodates', 'bathrooms', 'bed_type', 'cancellation_policy',
       'cleaning_fee', 'city', 'description', 'first_review',
       'host_has_profile_pic', 'host_identity_verified', 'host_response_rate',
       'host_since', 'instant_bookable', 'last_review', 'latitude',
       'longitude', 'name', 'neighbourhood', 'number_of_reviews',
       'review_scores_rating', 'thumbnail_url', 'zipcode', 'bedrooms', 'beds'],
      dtype='object')

In [61]:
df.describe()

,id,log_price,accommodates,bathrooms,latitude,longitude,number_of_reviews,review_scores_rating,bedrooms,beds
count,7.411100e+04,74111.000000,74111.000000,73911.000000,74111.000000,74111.000000,74111.000000,57389.000000,74020.000000,73980.000000
mean,1.126662e+07,4.782069,3.155146,1.235263,38.445958,-92.397525,20.900568,94.067365,1.265793,1.710868
std,6.081735e+06,0.717394,2.153589,0.582044,3.080167,21.705322,37.828641,7.836556,0.852143,1.254142
min,3.440000e+02,0.000000,1.000000,0.000000,33.338905,-122.511500,0.000000,20.000000,0.000000,0.000000
25%,6.261964e+06,4.317488,2.000000,1.000000,34.127908,-118.342374,1.000000,92.000000,1.000000,1.000000
50%,1.225415e+07,4.709530,2.000000,1.000000,40.662138,-76.996965,6.000000,96.000000,1.000000,1.000000
75%,1.640226e+07,5.220356,4.000000,1.000000,40.746096,-73.954660,23.000000,100.000000,1.000000,2.000000
max,2.123090e+07,7.600402,16.000000,8.000000,42.390437,-70.985047,605.000000,100.000000,10.000000,18.000000

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74111 entries, 0 to 74110
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      74111 non-null  int64
 1   log_price               74111 non-null  float64
 2   property_type           74111 non-null  object
 3   room_type               74111 non-null  object
 4   amenities               74111 non-null  object
 5   accommodates            74111 non-null  int64
 6   bathrooms               73911 non-null  float64
 7   bed_type                74111 non-null  object
 8   cancellation_policy     74111 non-null  object
 9   cleaning_fee            74111 non-null  bool
 10  city                    74111 non-null  object
 11  description             74111 non-null  object
 12  first_review            58247 non-null  object
 13  host_has_profile_pic    73923 non-null  object
 14  host_identity_verified  73923 non-null  object
 15  host_response_rate      55812 non-null  object
 16  host_since              73923 non-null  object
 17  instant_bookable        74111 non-null  object
 18  last_review             58284 non-null  object
 19  latitude                74111 non-null  float64
 20  longitude               74111 non-null  float64
 21  name                    74111 non-null  object
 22  neighbourhood           67239 non-null  object
 23  number_of_reviews       74111 non-null  int64
 24  review_scores_rating    57389 non-null  float64
 25  thumbnail_url           65895 non-null  object
 26  zipcode                 73145 non-null  object
 27  bedrooms                74020 non-null  float64
 28  beds                    73980 non-null  float64
dtypes: bool(1), float64(7), int64(3), object(18)
memory usage: 15.9+ MB

In [63]:
df.drop(['id','description','thumbnail_url','name','neighbourhood'],axis=1,inplace=True)
index = df.columns
for i in index:
    print(df[i].value_counts())

log_price
5.010635    2729
4.605170    2707
4.317488    2049
5.298317    1923
3.912023    1920
            ...
6.999422       1
6.725034       1
7.070724       1
6.156979       1
6.357842       1
Name: count, Length: 767, dtype: int64
property_type
Apartment             49003
House                 16511
Condominium            2658
Townhouse              1692
Loft                   1244
Other                   607
Guesthouse              498
Bed & Breakfast         462
Bungalow                366
Villa                   179
Dorm                    142
Guest suite             123
Camper/RV                94
Timeshare                77
Cabin                    72
In-law                   71
Hostel                   70
Boutique hotel           69
Boat                     65
Serviced apartment       21
Tent                     18
Castle                   13
Vacation home            11
Yurt                      9
Hut                       8
Treehouse                 7
Chalet                    6
Earth House               4
Tipi                      3
Train                     2
Cave                      2
Casa particular           1
Parking Space             1
Lighthouse                1
Island                    1
Name: count, dtype: int64
room_type
Entire home/apt    41310
Private room       30638
Shared room         2163
Name: count, dtype: int64
amenities
{}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               586
{"translation missing: en.hosting_amenity_49","translation missing: en.hosting_amenity_50"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      135
{"Family/kid friendly"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          103
{"Pets allowed","Family/kid friendly"}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            27
{TV,"Cable TV",Internet,"Wireless Internet","Air conditioning",Kitchen,"Pets allowed",Doorman,Gym,Elevator,Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector","Carbon monoxide detector",Essentials,Shampoo,"24-hour check-in",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Self Check-In",Doorman}                                                                                                                                                                                                                                                                            26
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ...
{TV,Internet,"Wireless Internet",Kitchen,"Free parking on premises","Pets live on this property",Cat(s),Heating,Washer,Dryer,"Smoke detector","Carbon monoxide detector",Essentials,Hangers,"Hair dryer",Iron,"Laptop friendly workspace","translation missing: en.hosting_amenity_49","translation missing: en.hosting_amenity_50"}                                                                                                                                                                                                                                                               1
{TV,Internet,"Air conditioning",Kitchen,"Pets allowed","Pets live on this property",Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector",Essentials,Shampoo,Hangers,Iron}                                                                                                                                                                                                                                                                                                                                                                                                                   1
{TV,"Cable TV",Internet,"Wireless Internet",Kitchen,"Pets allowed","Pets live on this property",Dog(s),Heating,"Family/kid friendly","Suitable for events","Smoke detector","Carbon monoxide detector","First aid kit","Safety card","Fire extinguisher",Essentials,Shampoo,"Lock on bedroom door","24-hour check-in",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","Childrenâ€™s books and toys","Hot water","Bed linens","Extra pillows and blankets",Microwave,"Coffee maker",Refrigerator,Dishwasher,"Dishes and silverware","Cooking basics",Oven,Stove,"Luggage dropoff allowed"}      1
{TV,Internet,"Wireless Internet","Air conditioning",Kitchen,Heating,"Family/kid friendly",Washer,Dryer,"24-hour check-in","Hair dryer",Iron,"Laptop friendly workspace","Self Check-In",Keypad}                                                                                                                                                                                                                                                                                                                                                                                                    1
{TV,Internet,"Wireless Internet",Kitchen,"Free parking on premises",Heating,"Family/kid friendly","Smoke detector","Carbon monoxide detector","First aid kit","Safety card","Fire extinguisher",Essentials,Shampoo,"24-hour check-in",Hangers,"Hair dryer","Laptop friendly workspace"}                                                                                                                                                                                                                                                                                                            1
Name: count, Length: 67122, dtype: int64
accommodates
2     31854
4     12066
1      9434
3      7794
6      4969
5      3444
8      1795
7       946
10      701
16      301
9       270
12      264
14      104
11       79
15       54
13       36
Name: count, dtype: int64
bathrooms
1.0    58099
2.0     7936
1.5     3801
2.5     1567
3.0     1066
3.5      429
4.0      286
0.5      209
0.0      198
4.5      116
5.0       72
8.0       41
5.5       39
6.0       24
6.5       12
7.0       10
7.5        6
Name: count, dtype: int64
bed_type
Real Bed         72028
Futon              753
Pull-out Sofa      585
Airbed             477
Couch              268
Name: count, dtype: int64
cancellation_policy
strict             32374
flexible           22545
moderate           19063
super_strict_30      112
super_strict_60       17
Name: count, dtype: int64
cleaning_fee
True     54403
False    19708
Name: count, dtype: int64
city
NYC        32349
LA         22453
SF          6434
DC          5688
Chicago     3719
Boston      3468
Name: count, dtype: int64
first_review
1/1/2017      293
1/22/2017     249
1/2/2016      221
1/2/2017      211
9/4/2017      193
             ...
12/9/2012       1
4/20/2012       1
11/29/2010      1
3/28/2011       1
12/1/2010       1
Name: count, Length: 2554, dtype: int64
host_has_profile_pic
t    73697
f      226
Name: count, dtype: int64
host_identity_verified
t    49748
f    24175
Name: count, dtype: int64
host_response_rate
100%    43254
90%      2277
80%      1113
0%        883
50%       611
        ...
39%         1
15%         1
31%         1
21%         1
6%          1
Name: count, Length: 80, dtype: int64
host_since
3/30/2015     246
2/14/2014     173
5/18/2015      83
9/16/2016      83
7/6/2015       82
             ...
4/8/2009        1
11/22/2009      1
2/28/2010       1
5/11/2009       1
8/23/2009       1
Name: count, Length: 3087, dtype: int64
instant_bookable
f    54660
t    19451
Name: count, dtype: int64
last_review
4/30/2017     1344
9/24/2017     1278
9/17/2017     1215
4/23/2017     1025
9/18/2017      832
              ...
12/11/2013       1
6/19/2014        1
10/26/2013       1
3/28/2011        1
12/28/2013       1
Name: count, Length: 1371, dtype: int64
latitude
40.744040    2
40.689275    2
40.690627    2
40.799829    2
37.773155    2
            ..
34.067385    1
40.669758    1
40.667614    1
40.831173    1
33.761096    1
Name: count, Length: 74058, dtype: int64
longitude
-73.949879     2
-118.371753    2
-73.949108     2
-73.956756     2
-73.931565     2
              ..
-73.989602     1
-73.998885     1
-118.350746    1
-87.645442     1
-118.192409    1
Name: count, Length: 73973, dtype: int64
number_of_reviews
0      15819
1       7106
2       4750
3       3661
4       2912
       ...
370        1
254        1
449        1
314        1
341        1
Name: count, Length: 371, dtype: int64
review_scores_rating
100.0    16215
98.0      4374
97.0      4087
96.0      4081
95.0      3713
93.0      3647
90.0      2852
99.0      2631
94.0      2618
80.0      2163
92.0      2064
91.0      1615
89.0      1120
87.0      1119
88.0      1056
85.0       625
86.0       512
60.0       444
84.0       438
83.0       403
82.0       211
70.0       196
73.0       157
81.0       126
75.0       101
20.0        97
78.0        94
40.0        90
79.0        83
76.0        76
77.0        74
67.0        66
74.0        39
72.0        38
50.0        30
65.0        28
68.0        20
71.0        14
69.0        13
63.0        11
53.0        10
64.0        10
47.0         5
30.0         4
62.0         3
66.0         3
55.0         3
57.0         3
27.0         2
35.0         1
49.0         1
58.0         1
54.0         1
56.0         1
Name: count, dtype: int64
zipcode
11211                                                   1618
90291                                                   1274
11221                                                   1198
11206                                                   1015
94110                                                    988
                                                        ...
20229                                                      1
95202\r\r\r\r\r\r\n\r\r\r\r\r\r\n\r\r\r\r\r\r\n94158       1
10002-2289                                                 1
92821                                                      1
11239                                                      1
Name: count, Length: 669, dtype: int64
bedrooms
1.0     49784
2.0     11351
0.0      6715
3.0      4309
4.0      1330
5.0       355
6.0       106
7.0        38
8.0        14
10.0       10
9.0         8
Name: count, dtype: int64
beds
1.0     45144
2.0     16704
3.0      6442
4.0      3065
5.0      1287
6.0       661
7.0       216
8.0       186
10.0       88
9.0        72
16.0       38
12.0       29
11.0       23
13.0       10
15.0        6
14.0        4
0.0         4
18.0        1
Name: count, dtype: int64

In [64]:
print(df.columns.size)
for column in df.columns:
    
    if df[column].isnull().sum() != 0:
        
        print("========================================")
        print("\n{} :- {},  dtypes : {}".format(column,df[column].isnull().sum(),df[column].dtypes))

24
========================================

bathrooms :- 200,  dtypes : float64
========================================

first_review :- 15864,  dtypes : object
========================================

host_has_profile_pic :- 188,  dtypes : object
========================================

host_identity_verified :- 188,  dtypes : object
========================================

host_response_rate :- 18299,  dtypes : object
========================================

host_since :- 188,  dtypes : object
========================================

last_review :- 15827,  dtypes : object
========================================

review_scores_rating :- 16722,  dtypes : float64
========================================

zipcode :- 966,  dtypes : object
========================================

bedrooms :- 91,  dtypes : float64
========================================

beds :- 131,  dtypes : float64

In [65]:
df.dropna(subset=['review_scores_rating'], inplace=True)

In [66]:
df.bathrooms.fillna(1,inplace=True)

In [67]:
df.dropna(subset=['first_review'], inplace=True)

In [68]:
df.host_has_profile_pic.fillna('f',inplace=True)

In [69]:
df.host_identity_verified.fillna('f',inplace=True)

In [70]:
mean_value = df['host_response_rate'].str.rstrip('%').astype(float).mean()
# Fill null values with the mean
df['host_response_rate'].fillna(mean_value, inplace=True)

In [71]:
df.dropna(subset=['host_since'], inplace=True)

In [72]:
df.dropna(subset=['zipcode'], inplace=True)

In [73]:
df['beds'].fillna(df['accommodates'], inplace=True)

In [74]:
def custom_fillna(value1, value2):
    if np.isnan(value1):
        return divmod(value2, 2)[0] + divmod(value2, 2)[1]
    else:
        return value1

# Apply the custom function to fill null values in 'column1'
df['bedrooms'] = df.apply(lambda row: custom_fillna(row['bedrooms'], row['beds']), axis=1)

In [75]:
print(df.columns.size)
for column in df.columns:
    
    if df[column].isnull().sum() != 0:
        
        print("========================================")
        print("\n{} :- {},  dtypes : {}".format(column,df[column].isnull().sum(),df[column].dtypes))

24

In [76]:
df.columns

Index(['log_price', 'property_type', 'room_type', 'amenities', 'accommodates',
       'bathrooms', 'bed_type', 'cancellation_policy', 'cleaning_fee', 'city',
       'first_review', 'host_has_profile_pic', 'host_identity_verified',
       'host_response_rate', 'host_since', 'instant_bookable', 'last_review',
       'latitude', 'longitude', 'number_of_reviews', 'review_scores_rating',
       'zipcode', 'bedrooms', 'beds'],
      dtype='object')

In [77]:
df['review_scores_rating'] = df['review_scores_rating'].apply(lambda x: 1 if x > 90 else 0)

In [78]:
# def satisfaction_bar(df):   
#     import matplotlib
#     import numpy as np
#     import matplotlib.pyplot as plt
#     plt.rcParams.update({'figure.max_open_warning': 0})
    
#     # names = df.columns.tolist()
#     selected_names= ['property_type','room_type','bed_type','cancellation_policy','cleaning_fee','city',
#                     'first_review','host_has_profile_pic','host_identity_verified','host_response_rate',
#                     'host_since','instant_bookable','last_review','zipcode']
#     for col in selected_names:
#         if(df[col].dtype not in [np.int64, np.int32, np.float64]):
#             temp1 = df.loc[df.review_scores_rating == 1, col].value_counts()
#             temp0 = df.loc[df.review_scores_rating == 0, col].value_counts() 
#             fig = plt.figure(figsize=(8,4))
#             fig.clf()
#             ax1 = fig.add_subplot(1, 2, 1)
#             ax0 = fig.add_subplot(1, 2, 2) 
#             temp1.plot(kind = 'bar', ax = ax1)
#             ax1.set_title('Values of ' + col + '\n for satisfied clients')
#             temp0.plot(kind = 'bar', ax = ax0)
#             ax0.set_title('Values of ' + col + '\n for not satisfied clients')
#             fig.savefig('bar_' + col + '.png')
#             print(col)
    
            
#     return 'Done'
# satisfaction_bar(df)

In [79]:
def codage_categorie(data):
    from sklearn import preprocessing

    le = preprocessing.LabelEncoder()
    for column_name in data.columns:
        if data[column_name].dtype == object and column_name != "host_response_rate":
            data[column_name] = le.fit_transform(data[column_name])
        else:
            pass
    return data

In [80]:
# df['host_response_rate'] = df['host_response_rate'].str.rstrip('%').astype(float)
df = codage_categorie(df)
# print(df['host_response_rate'])

property_type
room_type
amenities
bed_type

cancellation_policy
city
first_review
host_has_profile_pic
host_identity_verified
host_since
instant_bookable
last_review
zipcode

In [82]:
for i in df.columns:
    print(df[i].value_counts())

log_price
5.010635    1961
4.605170    1872
4.317488    1497
4.595120    1342
3.912023    1333
            ...
7.456455       1
7.150701       1
6.999422       1
6.049733       1
6.731018       1
Name: count, Length: 664, dtype: int64
property_type
0     37147
16    12913
10     1975
26     1273
20      996
21      419
14      404
1       352
4       304
30      126
11      113
13       98
6        67
5        62
18       62
15       55
3        47
2        44
24       32
22       15
23       14
7        13
17        7
28        6
29        6
31        6
9         5
25        3
12        3
27        2
8         2
19        1
Name: count, dtype: int64
room_type
0    32558
1    22592
2     1422
Name: count, dtype: int64
amenities
51981    187
7415      59
1221      49
23401     21
19858     19
        ...
1236       1
29802      1
20096      1
39886      1
50334      1
Name: count, Length: 51982, dtype: int64
accommodates
2     24615
4      9557
3      6206
1      5964
6      3914
5      2709
8      1427
7       773
10      553
16      215
9       211
12      203
14       89
11       68
15       39
13       29
Name: count, dtype: int64
bathrooms
1.0    44769
2.0     5998
1.5     2886
2.5     1128
3.0      797
3.5      289
4.0      216
0.0      145
0.5      137
4.5       75
5.0       51
5.5       25
8.0       25
6.0       14
6.5        8
7.0        5
7.5        4
Name: count, dtype: int64
bed_type
4    55003
2      597
3      480
0      337
1      155
Name: count, dtype: int64
cancellation_policy
2    27467
1    16272
0    12741
3       83
4        9
Name: count, dtype: int64
cleaning_fee
True     44914
False    11658
Name: count, dtype: int64
city
4    24581
3    16986
5     4990
2     4043
1     3175
0     2797
Name: count, dtype: int64
first_review
7       288
97      242
77      215
78      210
2510    189
       ...
863       1
838       1
958       1
801       1
607       1
Name: count, Length: 2551, dtype: int64
host_has_profile_pic
1    56480
0       92
Name: count, dtype: int64
host_identity_verified
1    41306
0    15266
Name: count, dtype: int64
host_response_rate
100%                 37506
95.54662305737261     9111
90%                   2039
80%                    945
70%                    431
                     ...
15%                      1
31%                      1
21%                      1
39%                      1
66%                      1
Name: count, Length: 78, dtype: int64
host_since
1038    158
1423    130
2892     71
2437     71
2488     66
       ...
1157      1
576       1
2141      1
1748      1
2648      1
Name: count, Length: 3055, dtype: int64
instant_bookable
0    41379
1    15193
Name: count, dtype: int64
last_review
694     1331
1291    1263
1252    1188
663     1016
1257     818
        ...
1096       1
1087       1
812        1
1288       1
378        1
Name: count, Length: 1351, dtype: int64
latitude
40.799829    2
41.895287    2
41.944495    2
34.045933    2
40.707911    2
            ..
40.671450    1
38.923652    1
34.138260    1
37.767727    1
33.761096    1
Name: count, Length: 56542, dtype: int64
longitude
-122.394396    2
-73.931875     2
-117.901666    2
-118.307003    2
-73.954970     2
              ..
-73.986371     1
-118.133079    1
-73.833569     1
-73.994991     1
-118.192409    1
Name: count, Length: 56491, dtype: int64
number_of_reviews
1      6232
2      4579
3      3575
4      2845
5      2470
       ...
347       1
279       1
425       1
250       1
341       1
Name: count, Length: 370, dtype: int64
review_scores_rating
1    44399
0    12173
Name: count, dtype: int64
zipcode
111    1260
414    1102
121     946
611     816
106     778
       ...
50        1
319       1
437       1
520       1
62        1
Name: count, Length: 631, dtype: int64
bedrooms
1.0     37827
2.0      8896
0.0      5234
3.0      3277
4.0       972
5.0       252
6.0        63
7.0        30
8.0        12
10.0        5
9.0         4
Name: count, dtype: int64
beds
1.0     33692
2.0     13202
3.0      5150
4.0      2420
5.0      1036
6.0       525
7.0       180
8.0       152
10.0       69
9.0        61
12.0       26
16.0       24
11.0       20
13.0        8
15.0        3
14.0        2
0.0         1
18.0        1
Name: count, dtype: int64

In [83]:
from sklearn.model_selection import train_test_split

y = df['readmitted']
x = df.drop('readmitted', axis=1)

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.4, random_state=5)

print('Train set:', x_train.shape)
print('Test set:', x_test.shape)

KeyError: 'readmitted'

In [ ]:

# def satisfaction_box(df):
#     import matplotlib
#     import numpy as np
#     import matplotlib.pyplot as plt
#     plt.rcParams.update({'figure.max_open_warning': 0})
    
#     names = df.columns.tolist()
#     for col in names:
#         if(df[col].dtype in [np.int64, np.int32, np.float64]):
#             temp1 = df.loc[df.review_scores_rating == 1, col]
#             temp0 = df.loc[df.review_scores_rating == 0, col]  
             
#             fig = plt.figure(figsize=(8,4))
#             fig.clf()
#             ax1 = fig.add_subplot(1, 2, 1)
#             ax0 = fig.add_subplot(1, 2, 2) 
#             ax1.boxplot(temp1.to_numpy())
#             ax1.set_title('Box plot of ' + col + '\n for readmitted patients')
#             ax0.boxplot(temp0.to_numpy())
#             ax0.set_title('Box plot of ' + col + '\n for patients not readmitted')
#             fig.savefig('box_' + col + '.png')

#     return 'Done'
    
# def satisfaction_hist(df):
#     import matplotlib
#     import numpy as np
#     import matplotlib.pyplot as plt
#     plt.rcParams.update({'figure.max_open_warning': 0})
    
#     names = df.columns.tolist()
#     for col in names:
#         if(df[col].dtype in [np.int64, np.int32, np.float64]):
#             temp1 = df.loc[df.review_scores_rating == 1, col]
#             temp0 = df.loc[df.review_scores_rating == 0, col]  
             
#             fig = plt.figure(figsize=(8,4))
#             fig.clf()
#             ax1 = fig.add_subplot(1, 2, 1)
#             ax0 = fig.add_subplot(1, 2, 2) 
#             ax1.hist(temp1.to_numpy(), bins = 30)
#             ax1.set_title('Histogram of ' + col + '\n for readmitted patients')
#             ax0.hist(temp0.to_numpy(), bins = 30)
#             ax0.set_title('Histogram of ' + col + '\n for patients not readmitted')
#             fig.savefig('hist_' + col + '.png')

#     return 'Done'